version: '3.8'

services:
  dmarcdefense-app:
    build: .
    container_name: dmarcdefensespoofingtool-dmarcdefense-app-1
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - SECRET_KEY=dmarcdefense_clave_secreta_2024
     - API_URL=${API_URL:-http://relay.dmarcd.net:5000/execute}
     - API_TOKEN=${API_TOKEN:-006ed549912bc9d6c43c477242b1724103caa02b}
    volumes:
      - ./instance:/app/instance
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/login"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
