version: '3.8'

services:
  dmarcdefense-app:
    build: .
    container_name: dmarcdefensespoofingtool-dmarcdefense-app-1
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - SECRET_KEY=dmarcdefense_clave_secreta_2024
    volumes:
      - ./instance:/app/instance
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/login"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
